{
    "openapi": "3.0.0",
    "info": {
        "title": "API's Xlearn",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "http://servicios.10xconsultores.org"
        },
        {
            "url": "http://127.0.0.1:8000"
        },
        {
            "url": "https://servicios.asstiseguridadsocial.com"
        }
    ],
    "paths": {
        "/api/v1/area/list": {
            "get": {
                "tags": [
                    "Areas"
                ],
                "summary": "Mostrar areas",
                "operationId": "703dcd0fcbcfe64954149ec3ce0bb25b",
                "parameters": [
                    {
                        "name": "offset",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mostrar todas las areas.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "response": {
                                            "hc:length": 0,
                                            "hc:total": 0,
                                            "hc:offset": 0,
                                            "hc:limit": 0,
                                            "hc:next": "next page end-point ",
                                            "hc:previous": "previous page end-point ",
                                            "_rel": "areas",
                                            "_embedded": {
                                                "areas": [
                                                    {
                                                        "id": 0,
                                                        "name": "",
                                                        "description": "",
                                                        "file_path": "",
                                                        "state": 0,
                                                        "created_at": "2022-06-11T23:21:42.000000Z",
                                                        "updated_at": "2022-06-12T00:46:06.000000Z"
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/content/list": {
            "get": {
                "tags": [
                    "Content"
                ],
                "summary": "Mostrar Los tipos de contenidos",
                "operationId": "5ddc247b95c8fd437171e96c7eefca74",
                "responses": {
                    "200": {
                        "description": "Mostrar todos los tipos de contenidos.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "roles": [
                                            {
                                                "id": 0,
                                                "name": ""
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/countries/list": {
            "get": {
                "tags": [
                    "Countries"
                ],
                "summary": "Mostrar Paises",
                "operationId": "3c15a70369eb61421ed10bb25594ec6c",
                "responses": {
                    "200": {
                        "description": "Mostrar todos los paises.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "countries": [
                                            {
                                                "id": 0,
                                                "name": ""
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/course/list": {
            "get": {
                "tags": [
                    "Courses"
                ],
                "summary": "Mostrar cursos",
                "operationId": "02708c6cb845c5a82a34d5daf197c9a9",
                "parameters": [
                    {
                        "name": "offset",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mostrar todos los cursos.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "response": {
                                            "hc:length": 0,
                                            "hc:total": 0,
                                            "hc:offset": 0,
                                            "hc:limit": 0,
                                            "hc:next": "next page end-point ",
                                            "hc:previous": "previous page end-point ",
                                            "_rel": "course",
                                            "_embedded": {
                                                "course": [
                                                    {
                                                        "id": 0,
                                                        "name": "",
                                                        "description": "",
                                                        "state": 0,
                                                        "free_video": "",
                                                        "file_path": "",
                                                        "video_path": "",
                                                        "area_id": 0,
                                                        "programs_id": 0,
                                                        "created_at": "2022-06-11T23:21:42.000000Z",
                                                        "updated_at": "2022-06-12T00:46:06.000000Z",
                                                        "areas": {
                                                            "id": 0,
                                                            "name": "",
                                                            "description": "",
                                                            "file_path": "",
                                                            "state": 0,
                                                            "created_at": "2022-06-11T23:21:42.000000Z",
                                                            "updated_at": "2022-06-12T00:46:06.000000Z"
                                                        }
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/course/show_area/{areaId}": {
            "get": {
                "tags": [
                    "Courses"
                ],
                "summary": "Mostrar curso por areas",
                "operationId": "47bb54f153b3f91eca1fa5f2e7673ce8",
                "parameters": [
                    {
                        "name": "offset",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mostrar todos los cursos del area.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "response": {
                                            "hc:length": 0,
                                            "hc:total": 0,
                                            "hc:offset": 0,
                                            "hc:limit": 0,
                                            "hc:next": "next page end-point ",
                                            "hc:previous": "previous page end-point ",
                                            "_rel": "course",
                                            "_embedded": {
                                                "course": [
                                                    {
                                                        "id": 0,
                                                        "name": "",
                                                        "description": "",
                                                        "state": 0,
                                                        "free_video": "",
                                                        "file_path": "",
                                                        "video_path": "",
                                                        "area_id": 0,
                                                        "programs_id": 0,
                                                        "created_at": "2022-06-11T23:21:42.000000Z",
                                                        "updated_at": "2022-06-12T00:46:06.000000Z",
                                                        "areas": {
                                                            "id": 0,
                                                            "name": "",
                                                            "description": "",
                                                            "file_path": "",
                                                            "state": 0,
                                                            "created_at": "2022-06-11T23:21:42.000000Z",
                                                            "updated_at": "2022-06-11T23:21:42.000000Z"
                                                        }
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Ingreso de usuarios",
                "operationId": "eabe0c74bd6109f926162392ae2fdd03",
                "parameters": [
                    {
                        "name": "email",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "schema": {
                            "type": "password"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Acceso correcto",
                                        "token": "",
                                        "datosUsuario": {
                                            "name": "",
                                            "email": "",
                                            "phone": ""
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/plan/list": {
            "get": {
                "tags": [
                    "Plans"
                ],
                "summary": "Mostrar Planes",
                "operationId": "ec79c94ffd1a354b936624da8849b002",
                "responses": {
                    "200": {
                        "description": "Mostrar todos los planes.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "plans": [
                                            {
                                                "id": 0,
                                                "name": "",
                                                "description": "",
                                                "price": "",
                                                "amount_people": "",
                                                "color_title": "",
                                                "color_border": ""
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/register_requests/list": {
            "get": {
                "tags": [
                    "Register request"
                ],
                "summary": "Mostrar solicitudes de registro",
                "operationId": "936e415f074f7a3c5d8f27ef0641c65f",
                "parameters": [
                    {
                        "name": "offset",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mostrar todas los solicitudes."
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/register_requests/store": {
            "post": {
                "tags": [
                    "Register request"
                ],
                "summary": "Crear solicitudes de registro",
                "operationId": "1ba777f1c5f4b36ad97e4f280d9843ab",
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "lastname",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "company",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "email",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "website",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "size",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "country",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "content",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "plan_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "quotas",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "observation",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "schema": {
                            "type": "password"
                        }
                    },
                    {
                        "name": "password_confirmation",
                        "in": "query",
                        "schema": {
                            "type": "password"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Registro almacenado con éxito."
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/register_requests/edit/{{id}}": {
            "put": {
                "tags": [
                    "Register request"
                ],
                "summary": "Actualizar solicitudes de registro",
                "operationId": "d7cdb5f06400ee91131981daff3b4a85",
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "lastname",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "company",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "email",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "website",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "size",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "country",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "content",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "plan_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "quotas",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "observation",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Registro actualizado con éxito."
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/roles/list": {
            "get": {
                "tags": [
                    "Roles"
                ],
                "summary": "Mostrar Roles de Usuarios",
                "operationId": "ea7fe64e1ebfa9569d8565cbdee34b9b",
                "responses": {
                    "200": {
                        "description": "Mostrar todos los roles de usuarios.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "roles": [
                                            {
                                                "id": 0,
                                                "name": ""
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/size/list": {
            "get": {
                "tags": [
                    "Company Size"
                ],
                "summary": "Mostrar Los Tamaños de empresas",
                "operationId": "0b62aecdd49e5837d74d02ac86a9a0df",
                "responses": {
                    "200": {
                        "description": "Mostrar todos los tamaños de empresas.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "roles": [
                                            {
                                                "id": 0,
                                                "range": "",
                                                "tag": ""
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/types_users/list": {
            "get": {
                "tags": [
                    "Type Users"
                ],
                "summary": "Mostrar Tipos de Usuarios",
                "operationId": "fbe9eb12d5f6cf769ace80c65d4d571d",
                "responses": {
                    "200": {
                        "description": "Mostrar todos los tipos de usuarios.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "types_users": [
                                            {
                                                "id": 0,
                                                "name": ""
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/user/store": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Crear usuarios",
                "operationId": "3a8979d7a0af6bed1d61687f1788c6b5",
                "parameters": [
                    {
                        "name": "type_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "rol_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "link_facebook",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "link_google",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "link_linkedin",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "link_instagram",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "surname",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "phone",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "email",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "subcompanies_id",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "schema": {
                            "type": "password"
                        }
                    },
                    {
                        "name": "password_confirmation",
                        "in": "query",
                        "schema": {
                            "type": "password"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Registro almacenado con éxito.",
                                        "id": 0
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/user/edit/{id}": {
            "put": {
                "tags": [
                    "Users"
                ],
                "summary": "Editar usuarios",
                "operationId": "0e18312d48c4e96c2c65fdaaf4129666",
                "parameters": [
                    {
                        "name": "type_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "rol_id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "link_facebook",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "link_google",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "link_linkedin",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "link_instagram",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "surname",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "phone",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "email",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "subcompanies_id",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "schema": {
                            "type": "password"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Usuario actualizado con éxto.",
                                        "id": 0
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/v1/user/list": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Mostrar usuarios",
                "operationId": "564a4398f7da5993c9e7719e6cd39305",
                "parameters": [
                    {
                        "name": "offset",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mostrar todos los usuarios.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "response": {
                                            "hc:length": 0,
                                            "hc:total": 0,
                                            "hc:offset": 0,
                                            "hc:limit": 0,
                                            "hc:next": "next page end-point ",
                                            "hc:previous": "previous page end-point ",
                                            "_rel": "users",
                                            "_embedded": {
                                                "users": [
                                                    {
                                                        "id": 0,
                                                        "name": "",
                                                        "lastname": "",
                                                        "company": "",
                                                        "email": "",
                                                        "website": "",
                                                        "size": 0,
                                                        "country_id": 0,
                                                        "content": "",
                                                        "plan_id": 0,
                                                        "quotas": 0,
                                                        "observation": "",
                                                        "created_at": "2022-06-11T23:21:42.000000Z",
                                                        "updated_at": "2022-06-12T00:46:06.000000Z",
                                                        "countries": {
                                                            "id": 0,
                                                            "name": ""
                                                        }
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Mensaje de error"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearer_token": {
                "type": "apiKey",
                "description": "Enter token in format (Bearer <token>)",
                "name": "Authorization",
                "in": "header"
            }
        }
    }
}